version: "3.3"
services:
  postgres-grpc-connector:
    container_name: postgres-grpc-connector
    image: qlikea/postgres-grpc-connector:latest
  postgres-database:
    container_name: postgres-database
    image: example/postgres-grpc-connector-database
  qix-engine:
    container_name: qix-engine
    image: qlikea/engine:12.71.0
    ports:
      - 9076:9076
    command: -S EnableGrpcCustomConnectors=1 -S GrpcConnectorPlugins="postgrea-grpc-connector,postgres-grpc-connector:50051"