version: "3.3"
services:
  postgres-grpc-connector:
    container_name: postgres-grpc-connector
    image: qlikea/postgres-grpc-connector:latest
    expose:
      - 50051
  postgres-database:
    container_name: postgres-database
    image: example/postgres-grpc-connector-database
    ports:
      - 5433:5432
  qix-engine:
    container_name: qix-engine
    image: qlikea/engine:12.71.0
    ports:
      - 9076:9076
    command: --legacyreload -S EnableGrpcCustomConnectors=1 -S GrpcConnectorPlugins="Postgres,postgres-grpc-connector:50051" -S EnableConnectivityService=0 -N
