version: "3.3"
services:
  postgres-database:
    container_name: postgres-database
    build: postgres-image/
  postgres-grpc-connector:
    container_name: postgres-grpc-connector
    image: qlikea/postgres-grpc-connector
  qix-engine:
    container_name: qix-engine
    image: qlikea/engine:12.84.0
    ports:
      - 9076:9076
    command: -S EnableGrpcCustomConnectors=1 -S GrpcConnectorPlugins="postgres-grpc-connector,postgres-grpc-connector:50051"
  node-test-runner:
    container_name: node-test-runner
    image: node:8
    working_dir: /reload-runner
    volumes:
      - ./reload-runner:/reload-runner
    # Creating node busybox
    command: "sh -c 'while :; do ping -c 1 google.com; sleep 60; done'"
