version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/postgres-grpc-connector
    environment:
      DOCKER_REPO: qlikcore/postgres-grpc-connector
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Linting
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status ./...
      - run:
          name: Build Docker Image
          command: |
            mkdir -p workspace
            VER="0.0.1-$CIRCLE_BUILD_NUM"
            echo "$VER" > workspace/version.txt
            docker build -t $DOCKER_REPO:$VER .
            docker save $DOCKER_REPO:$VER -o workspace/postgres-grpc-connector_image.tar
      - persist_to_workspace:
          root: workspace
          paths:
            - version.txt
            - postgres-grpc-connector_image.tar
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/postgres-grpc-connector
    environment:
      DOCKER_REPO: qlikcore/postgres-grpc-connector
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Import previously built docker image
          command: docker load < /tmp/workspace/postgres-grpc-connector_image.tar
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Spin up environment
          working_directory: ~/postgres-grpc-connector/example
          command: |
            VER=$(cat /tmp/workspace/version.txt)
            ACCEPT_EULA=yes TAG=:${VER} docker-compose up -d
            docker ps
            docker image ls
      - run:
          name: Execute tests on remote dockers
          working_directory: ~/postgres-grpc-connector/example/reload-runner
          command: |
            docker cp ./ node-test-runner:./reload-runner/
            docker exec node-test-runner sh -c 'npm install'
            docker exec node-test-runner sh -c 'npm run start:ci -s'

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build

